version: "3.1"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ExamplePassword
      MYSQL_DATABASE: isaa
      INNODB_FORCE_RECOVERY: 1
    ports:
      - "3306:3306"
